/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MvdE (https://sketchfab.com/MvdE)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-head-e869717813844a06ab340feb893a81aa
Title: Low-poly Head
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


import headScene from '../assets/3d/head.glb'

const Head = (props) => {  // Changed to arrow function syntax
  const { nodes, materials } = useGLTF(headScene)  // Use imported headScene
  const headRef = useRef()
  return (
    <group ref={headRef} {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.601}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.head}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_5.geometry}
            material={materials.hear}
          />
        </group>
      </group>
    </group>
  )
}

export default Head;